### ISSUE TITLE
Can't figure out how to use this...

### ISSUE THREAD

**Issue by agilemation** [node-ci/nci#1]
Hey there, 

I am very excited by the idea of a CI server written in Node.js and would love to contribute if that would be of any use?  Only thing is, I have no idea how I am supposed to use it?

Any pointers to get started firing it up?

Cheers,

James

**Comment by okv** [comment]
Hi, James.
nci is in active development right now. We plan to get first public version in a month or so.
After that it will be possible to discuss and implement features, fix bugs, etc.
Currently you can try development version by cloning current repository with git, `npm run sync` to install dependencies and `npm run dev` to get started server. But some things may not work as expected (or at all :) other can be changed in the future.
Thank you for your interest in nci project.

**Comment by agilemation** [comment]
Nice one!  I will give it a go now,  Thanks for  the pointers.

**Comment by okv** [comment]
released, please see repository main page
