### ISSUE TITLE
Integration with GitHub or Bitbucket

### ISSUE THREAD

**Issue by mistakster** [node-ci/nci#11]
Hi. I'm curious, if there is a simple way to catch GitHub's webhook and run build? As I see, your REST API is expecting valid `project` field, which is missing in the [webhook payload](https://developer.github.com/v3/activity/events/types/#pushevent). Any suggestions are welcome.

**Comment by okv** [comment]
Hi.
Currently no. It should be separate plugin (e.g. `nci-github-webhook`) which adds request listener which accepts request in github webhook format and runs building of a project.

**Comment by mistakster** [comment]
I see. Thanks.
