### ISSUE TITLE
[Suggestion] Use NodeGit for Git SCM

### ISSUE THREAD

**Issue by DeltaEvo** [node-ci/nci#31]
I think the git scm could use [NodeGit](http://www.nodegit.org/), this would make the code clearer and remove all git command output parsing

**Comment by okv** [comment]
NodeGit is awesome project and it can provide all benefits that you describe.
But for nci that's true only for local node/executor.
Current nci agentless architecture assumes implementation of Command (lib/command) abstraction.
From one side this abstraction is used to implement scm and other logic modules.
From other side when you implement remote node/executor (e.g. ssh, docker, etc) you should implement Command class (among others) for your environment and as a result you will get working scm (and other modules which use Command).
E.g. [ssh](https://github.com/node-ci/nci-ssh-node) and [docker](https://github.com/node-ci/nci-docker-node) nodes are implemented this way.
Such architecture has benefits and drawbacks but currently it's working this way and I don't plan to change it.
So I'm closing it.
Thanks for suggestion anyway.
