### ISSUE TITLE
Notify X when build failed or succeeded (hooks)

### ISSUE THREAD

**Issue by Rush** [node-ci/nci#7]
As in the title, is it possible to have success and failure notifications integrated with third party services? I am specifically interested in Slack integration.

**Comment by okv** [comment]
Notifications integrated with third party services should be done by creating [notifier transport plugin](https://github.com/node-ci/nci/tree/master/docs/developing-plugins#notifier-transport-plugin) for target service. See [mail](https://github.com/node-ci/nci-mail-notification),  [jabber](https://github.com/node-ci/nci-jabber-notification) notification plugins for example.

**Comment by bas00000009** [comment]
good

**Comment by jpic** [comment]
hi ! is there  plugin to update the commit status using  github api ?

**Comment by fleg** [comment]
@jpic hello, what do you mean? github webhooks?
