### ISSUE TITLE
Limit the changes list on the first build

### ISSUE THREAD

**Issue by ttyz** [node-ci/nci#9]
It is more of a suggestion. Maybe it would be better to limit the changes list to maybe last 100 commits. I am building the Linux kernel using nci and just retrieving the changes list takes like several minutes. left alone that amount of information on the screen becomes unmanageable. I would suggest having some kind of a "Show more" button which will then load all of the log messages.

**Comment by vladimir-polyakov** [comment]
Thanks.
It's good suggestion.
I think we can solve it in the upcoming release.

**Comment by okv** [comment]
Implemented at nci-classic-ui@0.7.9
